#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend gsmspace.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 451307-web-01 54.196.35.50:80 check
        server 451307-web-02 54.152.115.118:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
